---
# Basic light switch button - define its setting in substitutions
            height: ${hight}
            checkable: true
            id: lv_button_${id}
            widgets:
              - label:
                  text_font: $icon_font
                  align: top_left
                  text: $button_${id}_icon
                  id: lv_button_${id}_icon
              - label:
                  align: bottom_left
                  text: $button_${id}_name
            on_click:
                - homeassistant.service:
                    service: light.toggle
                    data:
                      entity_id: $button_${id}_device
