- id: '1732908024287'
  alias: Let's Encrypt renew
  description: Renew Let's Encrypt certs
  triggers:
  - trigger: time
    at: 03:00:00
  conditions: []
  actions:
  - action: hassio.addon_restart
    metadata: {}
    data:
      addon: core_letsencrypt
  mode: single
- id: '1732910862841'
  alias: Terrace Motion Light
  description: ''
  use_blueprint:
    path: gist.githubusercontent.com/motion_illuminance_activated_entity.yaml
    input:
      motion_sensor: binary_sensor.pir_terrace
      target_entity: switch.apb_q16
      sunstate_condition: Below horizon
      no_motion_wait: '2'
- id: '1733774848048'
  alias: pufi_childlock
  description: Force child lock on
  triggers:
  - type: pm25
    device_id: 38a9cf36a11b41fb1399bfd5227c8578
    entity_id: 453dd8ac556a75ec8539ad2c802ad375
    domain: sensor
    trigger: device
    above: 0
  conditions:
  - condition: device
    type: is_off
    device_id: 38a9cf36a11b41fb1399bfd5227c8578
    entity_id: 293da9e352721c087a4f2a54fe9ccb94
    domain: switch
  actions:
  - type: turn_on
    device_id: 38a9cf36a11b41fb1399bfd5227c8578
    entity_id: 293da9e352721c087a4f2a54fe9ccb94
    domain: switch
  mode: single
- id: '1735044244067'
  alias: Fish tank pump on
  description: ''
  triggers:
  - trigger: time
    at: 08:00:00
  conditions:
  - condition: state
    entity_id: switch.hg01wt_switch1
    state: 'off'
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.hg01wt_switch1
  mode: single
- id: '1735044398182'
  alias: Fish tank pump off
  description: ''
  triggers:
  - trigger: time
    at: '13:00:00'
  conditions:
  - condition: state
    entity_id: switch.hg01wt_switch1
    state: 'on'
  actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.hg01wt_switch1
  mode: single
