# Enable config via the interface
config:

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  time_zone: Europe/Budapest
  customize: !include_dir_merge_named customize
  customize_glob: !include customize_glob.yaml
  whitelist_external_dirs:
    - /config
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 127.0.0.1
    - type: legacy_api_password
      api_password: !secret api_password
      
#zone: !include zone.yaml
upnp:

zeroconf:

discovery:
  ignore:
    - yeelight
    - daikin

logger:
  default: warn
  logs:
    custom_components.programmable_thermostat.climate: warning
    homeassistant.components.cloud.google_config: error
    satel_integra.satel_integra: error
    homeassistant.components.binary_sensor: error
    homeassistant.components.modbus: info
    pymodbus.client: info
  
http:
  server_port: 443
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: https://gt.home.kg
  ip_ban_enabled: true
  login_attempts_threshold: 5

python_script:

map:

mobile_app:

cloud:

# Enable system health on info page
system_health:

## Enables support for tracking state changes over time.
#history:

## View all events in a logbook
#logbook:
#  include:
#    domains:
#      - sensor
#      - switch
#      - media_player
#      - climate
#  exclude:
#    entities:
#      - sensor.ac_target_temp
#      - sensor.ac_relay_up_time

## Configure the history of the logbook
#recorder:
#  db_url: sqlite:////config/home-assistant_v2.db
#  purge_interval: 1
#  purge_keep_days: 3
#  include:
#    domains:
#      - sensor
#      - switch
#      - media_player
#      - climate
#  exclude:
#    entities:
#      - sensor.ac_target_temp
#      - sensor.ac_relay_up_time

updater:

hacs:
  token: !secret hacs_token

# Text to speech&
tts:
  - platform: google_translate

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

shopping_list:

# Track the sun
sun:

saver:

modbus:
  name: apb
  type: serial
  method: rtu
  port: /dev/ttyUSB0
  baudrate: 9600
  stopbits: 1
  bytesize: 8
  parity: N
  timeout: 5
  
satel_integra: !include satel_integra.yaml

media_player:
  - platform: kodi
    host: qbox.lan
    port: 80
    tcp_port: 9090
    name: kodi
    username: !secret kodi_username
    password: !secret kodi_password
    
#tuya:
#  username: !secret tuya_username
#  password: !secret tuya_password
#  country_code: 36
#  platform: smart_life

yeelight:
  devices:
    192.168.1.41:
      name: dining_table
      #model: ceiling13
      nightlight_switch_type: light
      save_on_change: true
      transition: 350

huawei_lte:
  - url: http://192.168.8.1/
    username: !secret huawei_username
    password: !secret huawei_password
    notify:
      recipient: !secret huawei_notify_recipient

media_extractor:

frontend:
  themes: !include_dir_merge_named themes

# https://www.home-assistant.io/docs/automation/
automation: !include_dir_merge_list automations

# https://www.home-assistant.io/integrations/script/
#script: !include_dir_merge_named scripts

weather: !include_dir_merge_list integrations/weather
climate: !include_dir_merge_list integrations/climate
fan: !include_dir_merge_list integrations/fan
vacuum: !include_dir_merge_list integrations/vacuum
binary_sensor: !include_dir_merge_list integrations/binary_sensor
sensor: !include_dir_merge_list integrations/sensor
switch: !include_dir_merge_list integrations/switch
camera: !include_dir_merge_list integrations/camera

#input_boolean: !include_dir_merge_named integrations/input_boolean
#input_datetime: !include_dir_merge_named integrations/input_datetime
input_number: !include_dir_merge_named integrations/input_number
input_select: !include_dir_merge_named integrations/input_select
#input_text: !include_dir_merge_named integrations/input_text
utility_meter: !include_dir_merge_named integrations/utility_meter

#group: !include groups.yaml
person: !include person.yaml

lovelace:
  mode: yaml
  # Add yaml dashboards
  #dashboards:
  #  dashboard-2:
  #    mode: yaml
  #    title: Dashboard2
  #    icon: mdi:view-dashboard-outline
  #    show_in_sidebar: true
  #    filename: ui-lovelace.yaml
  resources:
    - url: /local/css/overrides.css
      type: css
    - url: /hacsfiles/custom-header/custom-header.js # /community_plugin/custom-header/custom-header.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-battery-entity/battery-entity.js
      type: module
    - url: /hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/lovelace-thermostat-card/main.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/rgb-light-card/card.js
      type: module
    - url: /hacsfiles/power-wheel-card/power-wheel-card.js?v=1
      type: module
    #- url: /hacsfiles/lovelace-google-keep-card/google-keep-card.js
    #  type: module
