# Enable config via the interface
config:

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  external_url: https://gt.home.kg
  internal_url: https://gt.home.kg
  unit_system: metric
  time_zone: Europe/Budapest
  country: HU
  currency: HUF
  #media_dirs:
  #  media: "/media"
  #  recordings: "/mnt/recordings"

  customize: !include_dir_merge_named customize
  customize_glob: !include customize_glob.yaml

  allowlist_external_dirs:
    - /config
  auth_providers:
    - type: homeassistant
#   - type: trusted_networks
#     trusted_networks:
#       - 192.168.1.0/24
#       - 127.0.0.1
    - type: legacy_api_password
      api_password: !secret api_password
      
#zone: !include zone.yaml

zeroconf:
ssdp:
dhcp:

logger:
  default: warn
  logs:
    homeassistant.loader: error
    homeassistant.components.system_log.external: info
    custom_components.programmable_thermostat.climate: info
    homeassistant.components.cloud.google_config: error
    satel_integra.satel_integra: error
    miio.miioprotocol: fatal
    custom_components.aquaariston.aristonaqua: error
    homeassistant.components.binary_sensor: error
    homeassistant.components.ipp: fatal
    homeassistant.components.nut: fatal
    homeassistant.components.xiaomi_miio.vacuum: error
    custom_components.xiaomi_miio_airpurifier.fan: fatal
    homeassistant.components.http: info
    custom_components.xiaomi_cloud_map_extractor: fatal
#    homeassistant.components.daikin: debug
#    pydaikin: debug
#    homeassistant.components.modbus: info
#    pymodbus.client: fatal
  
http:
  server_port: 443
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 50
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.5
    - 192.168.1.1


stream:

python_script:

#map:

mobile_app:
tag:

#cloud:

# Enable system health on info page
system_health:

## Configure the history of the logbook
recorder:
  db_url: mysql://homeassistant:K9cdXAIVbG62TRna@core-mariadb/homeassistant?charset=utf8
  commit_interval: 20
  purge_keep_days: 42
  include:
    domains:
      - binary_sensor
      - switch
      - media_player
      - climate
      - light
      - person
      - device_tracker
      - weather
      - input_number
      - input_select
      - water_heater
    entity_globs:
      - sensor.ac_*
      - sensor.*temp*
      - sensor.*power*
      - sensor.*_kwh
      - sensor.*_energy
      - sensor.*_cost*
      - sensor.*_compensation
      - sensor.*current*
      - sensor.*location*
      - sensor.*_geokodolt_hely
      - sensor.*_eszlelt_tevekenyseg
      - sensor.*_detected_activity
      - sensor.ble_*
    entities:
      - sensor.aqua_ariston_average_showers
      - sensor.aqua_ariston_energy_use_in_the_last_day
      - sensor.dishwasher
      - sensor.ble_measured_power_ibeacon
  exclude:
    entity_globs:
      - switch.*_led
      - switch.*_backlight
      - sensor.*_time
      - switch.energy_re*
      - input_number.energy_*
      - binary_sensor.*_pulse
    entities:
      - sensor.ble_mac_ibeacon

## Enables support for tracking state changes over time.
history:
logbook:

#influxdb:
#  api_version: 2
#  ssl: true
#  host: !secret influxdb_host
#  #port: 9999
#  token: !secret influxdb_token
#  organization: !secret influxdb_org
#  bucket: !secret influxdb_bucket
#  tags:
#    source: HA
#  tags_attributes:
#    - friendly_name
#  default_measurement: units
#  default_measurement: state
#  include:
#    domains:
#      - switch
#      - media_player
#      - climate
#      - light
#    entity_globs:
#      - sensor.ac_*
#      - sensor.*temp*
#  exclude:
#    entities:
#      - zone.home
#      - sensor.ac_relay_up_time
#    domains:
#      - persistent_notification
#      - person

media_source:

hacs:
  token: !secret hacs_token

# Text to speech&
tts:
  - platform: google_translate
    language: "hu"

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

shopping_list:

# Track the sun
sun:

energy:

saver:

satel_integra: !include satel_integra.yaml

media_player:
  - platform: kodi
    host: 192.168.1.9
    port: 80
    tcp_port: 9090
    name: QBox
    username: !secret kodi_username
    password: !secret kodi_password

media_extractor:

#tuya:
#  username: !secret tuya_username
#  password: !secret tuya_password
#  country_code: 36
#  platform: smart_life

yeelight:
  devices:
    192.168.1.41:
      name: dining_table
      model: ceiling10
      nightlight_switch_type: light
      save_on_change: false
      transition: 350

huawei_lte:
  - url: http://192.168.8.1/
    username: !secret huawei_username
    password: !secret huawei_password
    notify:
      recipient: !secret huawei_notify_recipient

aquaariston:
  username: !secret ariston_username
  password: !secret ariston_password
  type: velis
  polling: 2.0
  store_config_files: true
  switches:
    - eco                             # switches ECO mode
    - power                           # switches power
  binary_sensors:
    - antilegionella                  # indicates antilegionella status
    - changing_data                   # indicates ongoing configuration on server by the API
    - eco                             # indicates ECO mode status
    - heating                         # indicates ongoing heating
    - online                          # indicates API online status
    - power                           # indicates power status
    - update                          # indicates API update
  sensors:
    - antilegionella_set_temperature  # antilegionella temperature
    - current_temperature             # current temperature
    - energy_use_in_day               # energy use in last day
    - energy_use_in_month             # energy use in last week
    - energy_use_in_week              # energy use in last month
    - energy_use_in_year              # energy use in last year
    - errors                          # errors
    - mode                            # manual or time program mode
    - remaining_time                  # remaining time for heating
    - required_showers                # required amount of showers (might not work on all models)
    - required_temperature            # required temperature (simulated by API itself for some models)
    - showers                         # estimated amount of average showers
    - temperature_mode                # indicates if required temeparture is based on required temperature or required showers
    - time_program                    # time program schedule
  selector:
    - mode                            # boiler mode selector

#aquaariston: !include integrations/aquaariston.yaml

calendar:
  - platform: ics_calendar
    calendars:
      - name: ics1
        url: !secret ics_url1
        include_all_day: False
        days: 5
      - name: ics2
        url: !secret ics_url2
        include_all_day: False
        days: 5

frontend:
  themes: !include_dir_merge_named themes

# https://www.home-assistant.io/docs/automation/
automation: !include_dir_merge_list automations

# https://www.home-assistant.io/integrations/script/
script: !include_dir_merge_named scripts

binary_sensor: !include_dir_merge_list integrations/binary_sensor
camera: !include_dir_merge_list integrations/camera
climate: !include_dir_merge_list integrations/climate
fan: !include_dir_merge_list integrations/fan
sensor: !include_dir_merge_list integrations/sensor
switch: !include_dir_merge_list integrations/switch
template: !include_dir_merge_list integrations/template
utility_meter: !include_dir_merge_named integrations/utility_meter
#vacuum: !include_dir_merge_list integrations/vacuum
weather: !include_dir_merge_list integrations/weather

#input_boolean: !include_dir_merge_named integrations/input_boolean
#input_datetime: !include_dir_merge_named integrations/input_datetime
input_number: !include_dir_merge_named integrations/input_number
input_select: !include_dir_merge_named integrations/input_select
#input_text: !include_dir_merge_named integrations/input_text

#group: !include group.yaml
person: !include person.yaml

lovelace:
  mode: yaml
  # Add yaml dashboards
  #dashboards:
  #  dashboard-2:
  #    mode: yaml
  #    title: Dashboard2
  #    icon: mdi:view-dashboard-outline
  #    show_in_sidebar: true
  #    filename: ui-lovelace.yaml
  resources: !include ui-resources.yaml
