title: Cékla 3.
custom_header:
  compact_mode: false
  split_mode: false
  footer_mode: false
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)
views:
  - path: apb
    #title: Villany
    icon: mdi:lightbulb-multiple-outline
    # badges:
    #   - entity: binary_sensor.apb_i0
    #   - entity: binary_sensor.apb_i19
    #   - entity: binary_sensor.apb_i1a
    #   - entity: binary_sensor.apb_i1b
    #   - entity: binary_sensor.apb_i1c
    #   - entity: binary_sensor.apb_i5
    #   - entity: binary_sensor.apb_i3
    #   - entity: binary_sensor.apb_i6
    #   - entity: binary_sensor.apb_i4
    #   - entity: binary_sensor.apb_i7
    #   - entity: binary_sensor.apb_i8
    #   - entity: binary_sensor.apb_i9
    #   - entity: binary_sensor.apb_ia
    #   - entity: binary_sensor.apb_ib
    #   - entity: binary_sensor.apb_ic
    #   - entity: binary_sensor.apb_id
    #   - entity: binary_sensor.apb_i12
    #   - entity: binary_sensor.apb_i13
    #   - entity: binary_sensor.apb_i14
    #   - entity: binary_sensor.apb_i1
    #   - entity: binary_sensor.apb_i15
    #   - entity: binary_sensor.apb_i2
    #   - entity: binary_sensor.apb_i16
    #   - entity: binary_sensor.apb_i17
    #   - entity: binary_sensor.apb_i18
    cards:
      - type: entities
        title: 'Hálószoba RGB'
        show_header_toggle: true
        entities:
          - type: custom:slider-entity-row
            entity: light.bedroom_rgb
            name: 'Fényerő'
            hide_when_off: true
            min: 11
            step: 5
            tap_action:
              action: toggle
          - type: custom:rgb-light-card
            entity: light.bedroom_rgb
            hide_when_off: true
            justify: right
            colors:
              - rgb_color: [255, 255, 255]
                icon_color: '#FEFEFE'
              - rgb_color: [0, 0, 255]
                icon_color: '#0000FF'
              - rgb_color: [51, 102, 204]
                icon_color: '#3366CC'
              - rgb_color: [0, 255, 255]
                icon_color: '#00FFFF'
              - rgb_color: [51, 204, 51]
                icon_color: '#33CC33'
              - rgb_color: [255, 0, 255]
                icon_color: '#FF00FF'
              - rgb_color: [255, 255, 64]
                icon_color: '#FFFF40'
              - rgb_color: [255, 126, 0]
                icon_color: '#FF7E00'
              - rgb_color: [255, 0, 0]
                icon_color: '#D50000'
      - type: entities
        title: 'Étkezőasztal'
        show_header_toggle: true
        entities:
          - type: custom:slider-entity-row
            entity: light.dining_table
            name: 'Fő'
            toggle: true
            hide_when_off: true
            min: 5
            step: 10
          #- type: custom:slider-entity-row
          #  entity: light.dining_table
          #  attribute: color_temp
          #  name: 'Színhőmérséklet'
          #  icon: mdi:invert-colors
          #  hide_when_off: true
          #  step: 10
          - type: custom:slider-entity-row
            entity: light.dining_table_ambilight
            name: 'Hangulat'
            toggle: true
            hide_when_off: true
            min: 5
            step: 10
          - type: custom:rgb-light-card
            entity: light.dining_table_ambilight
            hide_when_off: true
            justify: right
            colors:
              - rgb_color: [255, 255, 255]
                icon_color: '#FEFEFE'
              - rgb_color: [0, 0, 255]
                icon_color: '#0000FF'
              - rgb_color: [51, 102, 204]
                icon_color: '#3366CC'
              - rgb_color: [0, 255, 255]
                icon_color: '#00FFFF'
              - rgb_color: [51, 204, 51]
                icon_color: '#33CC33'
              - rgb_color: [255, 0, 255]
                icon_color: '#FF00FF'
              - rgb_color: [255, 255, 64]
                icon_color: '#FFFF40'
              - rgb_color: [255, 64, 0]
                icon_color: '#FF4000'
              - rgb_color: [255, 0, 0]
                icon_color: '#D50000'
      - type: glance
        show_state: false
        columns: 3
        entities:
          - entity: switch.apb_q0
            tap_action:
              action: toggle
          - entity: switch.apb_q1
            tap_action:
              action: toggle
          - entity: switch.apb_q2
            tap_action:
              action: toggle
          - entity: switch.apb_q3
            tap_action:
              action: toggle
          - entity: switch.apb_q4
            tap_action:
              action: toggle
          - entity: switch.apb_q5
            tap_action:
              action: toggle
          - entity: switch.apb_q6
            tap_action:
              action: toggle
          - entity: switch.apb_q7
            tap_action:
              action: toggle
          - entity: switch.apb_q10
            tap_action:
              action: toggle
          - entity: switch.apb_q11
            tap_action:
              action: toggle
          - entity: switch.apb_q12
            tap_action:
              action: toggle
          - entity: switch.apb_q13
            tap_action:
              action: toggle
          - entity: switch.apb_q17
            tap_action:
              action: toggle
          - entity: switch.apb_m1
            tap_action:
              action: toggle
          - entity: switch.apb_q14
            tap_action:
              action: toggle
          - entity: switch.apb_q15
            tap_action:
              action: toggle
          - entity: switch.apb_q16
            tap_action:
              action: toggle

          - entity: switch.apb_m0
            tap_action:
              action: toggle

  - path: ac
    #title: AC
    icon: mdi:air-conditioner
    #panel: true
    badges:
      - entity: sensor.study_temp
      - entity: sensor.childa_temp
      - entity: sensor.childa_humidity
      - entity: sensor.childb_temp
      - entity: sensor.childb_humidity
      - entity: sensor.childb_temp_outside
      - entity: sensor.bedroom_temp
      - entity: sensor.bedroom_humidity
      - entity: sensor.livingroom_temp
      - entity: sensor.livingroom_humidity
      - entity: sensor.io_temp_diff
      - entity: sensor.ac_sensor_temp_ac_outlet
      - entity: sensor.ac_sensor_temp_ac_gas_tube
      - entity: sensor.ac_inside_temperature
    cards:
      - type: custom:layout-card
        layout: horizontal
        min_columns: 2
        cards:
        - type: custom:thermostat-card
          entity: climate.ac
          ambient_temperature: sensor.livingroom_temp
          title: AC
          pending: 0
        - type: custom:thermostat-card
          entity: climate.ac_study
          title: Dolgozó
          pending: 0
        - type: custom:thermostat-card
          entity: climate.ac_childa
          title: Máté
          pending: 0
        - type: custom:thermostat-card
          entity: climate.ac_childb
          title: Milán
          pending: 0
        - type: custom:thermostat-card
          entity: climate.ac_bedroom
          title: Háló
          pending: 0
        - type: custom:thermostat-card
          entity: climate.ac_kitchen
          title: Konyha
          pending: 0
      - type: entities
        title: Ventillátor
        show_header_toggle: false
        entities:
        - entity: fan.ac
          type: custom:slider-entity-row
          name: AC
          attribute: speed
          min: 1
          max: 5
      - type: entities
        title: Automatizálás
        entities:
          - entity: automation.ventillation_auto_off
            secondary_info: last-triggered
          - entity: automation.ventillation_auto_on
            secondary_info: last-triggered
      - type: entities
        title: Kapcsoló
        entities:
          - switch.ac_relay_study
          - switch.ac_relay_childa
          - switch.ac_relay_childb
          - switch.ac_relay_bedroom
          - switch.ac_relay_kitchen
          - switch.ac_relay_ventillation
      - type: vertical-stack
        cards:
        - type: picture-entity
          entity: camera.weather
        - type: weather-forecast
          entity: weather.owm

  - path: energy
    icon: mdi:flash
    badges:
      - entity: sensor.energy_voltage1
        name: Feszültség 1
      - entity: sensor.energy_voltage2
        name: Feszültség 2
      - entity: sensor.energy_voltage3
        name: Feszültség 3
      - entity: sensor.energy_freq1
        name: Frekvencia 1
      - entity: sensor.energy_freq2
        name: Frekvencia 2
      - entity: sensor.energy_freq3
        name: Frekvencia 3
      - entity: sensor.energy_pf1
        name: Áramfaktor 1
      - entity: sensor.energy_pf2
        name: Áramfaktor 2
      - entity: sensor.energy_pf3
        name: Áramfaktor 3
    cards:
      - type: entity-filter
        card:
          type: glance
        entities:
          - type: sensor
            entity: sensor.energy_current1
            name: Áramerősség 1
          - type: sensor
            entity: sensor.energy_current2
            name: Áramerősség 2
          - type: sensor
            entity: sensor.energy_current3
            name: Áramerősség 3
        state_filter:
          - operator: "!="
            value: unavailable
        show_empty: false
      - type: entity-filter
        card:
          type: glance
        entities:
          - type: sensor
            entity: sensor.energy_power1
            name: P. teljesítmény 1
          - type: sensor
            entity: sensor.energy_power2
            name: P. teljesítmény 2
          - type: sensor
            entity: sensor.energy_power3
            name: P. teljesítmény 3
        state_filter:
          - operator: "!="
            value: unavailable
        show_empty: false
      - type: entity-filter
        card:
          type: glance
        entities:
          - type: sensor
            entity: sensor.energy_energy1
            name: Fogyasztás 1
          - type: sensor
            entity: sensor.energy_energy2
            name: Fogyasztás 2
          - type: sensor
            entity: sensor.energy_energy3
            name: Fogyasztás 3
        state_filter:
          - operator: "!="
            value: unavailable
        show_empty: false
      - type: entity-filter
        card:
          type: glance
        entities:
          - type: button
            entity: switch.energy_reset1
            name: 1
            icon: mdi:numeric-0
          - type: button
            entity: switch.energy_reset2
            name: 2
            icon: mdi:numeric-0
          - type: button
            entity: switch.energy_reset3
            name: 3
            icon: mdi:numeric-0
          - type: button
            entity: switch.energy_restart
            name: Újraindfítás
            icon: mdi:reload
        state_filter:
          - operator: "!="
            value: unavailable
        show_empty: false

  - path: alarm
    #title: Riasztó
    icon: mdi:shield-home
    badges:
      - entity: binary_sensor.pir_entry
      - entity: binary_sensor.pir_study
      - entity: binary_sensor.pir_bedroom
      - entity: binary_sensor.pir_kitchen
      - entity: binary_sensor.pir_livingroom
      - entity: binary_sensor.pir_childa
      - entity: binary_sensor.pir_childb
      - entity: binary_sensor.window_study
      - entity: binary_sensor.window_bedroom
      - entity: binary_sensor.window_bathroom
      - entity: binary_sensor.window_kitchen
      - entity: binary_sensor.window_livingroom1
      - entity: binary_sensor.window_livingroom2
      - entity: binary_sensor.window_childa
      - entity: binary_sensor.window_childb
      - entity: binary_sensor.dusk_detector
      - entity: binary_sensor.pir_terrace
      - entity: binary_sensor.pir_backyard_left
      - entity: binary_sensor.pir_backyard_back
      - entity: binary_sensor.pir_backyard_right
      - entity: binary_sensor.pir_backyard_sidewalk
      - entity: binary_sensor.fire_attic
      - entity: binary_sensor.alarm_armed_fully
      - entity: binary_sensor.alarm_tamper
    cards:
      - type: alarm-panel
        entity: alarm_control_panel.inside
      - type: alarm-panel
        entity: alarm_control_panel.windows
      - type: alarm-panel
        entity: alarm_control_panel.outside
      - type: entities
        entities:
          - switch.alarm_output1
          - switch.alarm_output2
          - switch.alarm_sirene_buzzer
          - switch.alarm_sirene_light
          - switch.terrace_light
          - switch.outside_wall_light1
          - switch.outside_wall_light2
  - path: pufi
    #title: Pufi
    icon: mdi:air-purifier
    badges:
      - entity: sensor.pufi_speed
      - entity: sensor.pufi_filter_remaining
      - entity: sensor.pufi_air_quality_pm25
      - entity: sensor.pufi_temp
      - entity: sensor.pufi_humidity
    cards:
      - type: entities
        show_header_toggle: false
        state_color: true
        entities:
          - fan.pufi
          - input_number.pufi_level
          - input_select.pufi_mode
          - switch.pufi_child_lock
          - switch.pufi_led
          - switch.pufi_buzzer
  - path: roberta
    #title: Roberta
    icon: mdi:robot-vacuum
    panel: false
    cards:
      - type: custom:xiaomi-vacuum-card
        entity: vacuum.roberta
        image: /local/img/roberta.jpg
        name: Roberta
        vendor: Xiaomi
        buttons:
          spot: true
        icons:
          locate: mdi:map-marker-question-outline
          spot: mdi:map-marker-radius-outline
          return: mdi:map-marker-right-outline
        labels:
          status: Státusz
          battery: Akku
          mode: Mód
          main_brush: Fő seprű
          side_brush: Oldalső seprű
          filter: Filter
          sensor: Szenzor
  - path: other
    #title: Egyéb
    icon: mdi:asterisk
    badges:
      - entity: person.gt
      - entity: person.gsm
      - entity: sensor.moon
      - entity: sun.sun
    cards:
      - type: media-control
        entity: media_player.kodi
      - type: custom:power-wheel-card
        solar_power_entity: sensor.solaredge_ac_power
        grid_power_entity: sensor.solaredge_ac_power
        #solar_energy_entity: sensor.solaredge_ac_energy_kwh
        #grid_energy_entity: sensor.solaredge_ac_energy_kwh
      - type: entities
        title: Solar energy
        entities:
        - sensor.solar_production_hourly
        - sensor.solar_production_daily
        - sensor.solar_production_weekly
        - sensor.solar_production_monthly
        - sensor.solaredge_ac_energy_kwh
        - sensor.solaredge_ac_current
        - sensor.solaredge_ac_power
      - type: vertical-stack
        title: UPS
        cards:
          - type: entities
            entities:
            - sensor.eaton_status_data
            - type: custom:battery-entity
              entity: sensor.eaton_battery_charge
            - sensor.eaton_battery_runtime
            - sensor.eaton_load
      - type: entities
        title: Kapcsoló
        entities:
          - switch.red_led
          - switch.yellow_led
          - switch.green_led
