title: Cékla 3.
custom_header:
  compact_mode: false
  split_mode: false
  footer_mode: false
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)
views: !include_dir_merge_list views
