- platform: template
  switches:
    humi1_buzzer:
      friendly_name: "Buzzer"
      value_template: "{{ is_state_attr('fan.humi1', 'buzzer', True) }}"
      turn_on:
        service: xiaomi_miio_airpurifier.fan_set_buzzer_on
        data:
          entity_id: fan.humi1
      turn_off:
        service: xiaomi_miio_airpurifier.fan_set_buzzer_off
        data:
          entity_id: fan.humi1
      icon_template: "mdi:volume-off"

    humi1_led:
      friendly_name: "LED"
      value_template: "{{ is_state_attr('fan.humi1', 'led', True) }}"
      turn_on:
        service: xiaomi_miio_airpurifier.fan_set_led_on
        data:
          entity_id: fan.humi1
      turn_off:
        service: xiaomi_miio_airpurifier.fan_set_led_off
        data:
          entity_id: fan.humi1
      icon_template: "mdi:lightbulb-outline"
