esp8266:
  board: d1_mini
  restore_from_flash: true

esphome:
  on_boot:
    priority: 200
    then:
       - lambda: 'WiFi.setPhyMode(WIFI_PHY_MODE_11G);'

light:
  - platform: status_led
    id: led_status
    pin:
      number: D4
      inverted: true
