esp8266:
  board: esp12e
  restore_from_flash: true

esphome:
  on_boot:
    priority: 200
    then:
       - lambda: 'WiFi.setPhyMode(WIFI_PHY_MODE_11G);'

status_led:
  pin:
    number: GPIO2
    inverted: true
