esphome:
  platformio_options:
    monitor_speed: 115200
    upload_speed: 921600

esp32:
  board: esp32dev #esp32-c3-devkitm-1
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
    # Advanced tweaking options
    advanced:
      ignore_efuse_mac_crc: false

network:
    enable_ipv6: true

status_led:
  pin:
    number: GPIO33
    inverted: true
