esphome:
  name: ${name}
  platformio_options:
    board_build.flash_mode: dout
    board_build.ldscript: eagle.flash.1m.ld
    upload_resetmethod: nodemcu

esp8266:
  board: esp01_1m

status_led:
  pin:
    number: GPIO2
    inverted: true
