esphome:
  name: ${name}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .lan
  fast_connect: false
  reboot_timeout: 2min

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} fallback"
    password: !secret ap_password
    ap_timeout: 10min

captive_portal:

# Enable logging
logger:

# Enable Web server
web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_enc_key
  reboot_timeout: 5min

ota:
  password: !secret ota_password
  num_attempts: 5

time:
  - platform: homeassistant
    id: hatime

sensor:
# Extra sensor to keep track of plug uptime
  - platform: uptime
    id: up_time
    name: ${name}_up_time
    icon: "mdi:timelapse"
  - platform: wifi_signal
    name: ${name}_wifi_signal
    update_interval: 30s

binary_sensor:
  - platform: status
    name: ${name}_status
    id: system_status

switch:
  - platform: restart
    name: ${name}_restart
