
packages:
  minimal: !include minimal.yaml

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name}
    password: !secret ap_password
    ap_timeout: 5min

captive_portal:


# Enable Web server
web_server:
  port: 80
  version: 3
  auth:
    username: admin
    password: !secret web_server_password

sensor:
  - platform: uptime
    id: up_time
    name: ${name}_up_time
    icon: "mdi:timelapse"
    disabled_by_default: true
  - platform: wifi_signal
    name: ${name}_wifi_signal
    update_interval: 30s
    icon: "mdi:signal-variant"
    disabled_by_default: true

binary_sensor:
  - platform: status
    name: ${name}_status
    id: system_status
    icon: "mdi:power"
    disabled_by_default: true

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${name}_wifi_ip
      id: wifi_ip
      icon: "mdi:ip"
      disabled_by_default: true
    ssid:
      name: ${name}_wifi_ssid
      id: wifi_ssid
      icon: "mdi:wifi-check"
      disabled_by_default: true
    mac_address:
      name: ${name}_wifi_mac
      id: wifi_mac
      icon: "mdi:hexadecimal"
      disabled_by_default: true

switch:
  - platform: restart
    name: ${name}_restart
    icon: "mdi:restart"
    disabled_by_default: true
