packages:
  common: !include common.yaml
  board: !include board/cb2s.yaml

substitutions:
  sw_icon: "mdi:switch"
  sw1_name: "sw1"
  sw1_inverted: "no"

switch:
- platform: gpio
  id: sw1
  name: ${name}_${sw1_name}
  icon: ${sw_icon}
  pin:
    number: P24
    inverted: ${sw1_inverted}

binary_sensor:
- platform: gpio
  id: sw_all
  name: ${name}_all
  pin:
    number: P8
    inverted: true
    mode: INPUT_PULLUP
  on_press:
    then:
    - switch.toggle: sw1
