packages:
  common: !include common.yaml
  board: !include board/magichome.yaml

# this is code for the monochromatic version of magichome 
light:
  - platform: monochromatic
    name: ${name}
    output: pwm1

output:
  - platform: esp8266_pwm
    id: pwm1
    pin: GPIO12
    frequency: 1000 Hz
