substitutions:
  name: magichome_rgb

esphome:
  name: ${name}
  platform: ESP8266
  board: esp8285
  esp8266_restore_from_flash: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} fallback hotspot"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:
  #level: INFO

# Enable Web server
web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

time:
  - platform: homeassistant
    id: hatime

# this is code for the RGBW version of magichome 
light:
  - platform: rgbw
    name: ${name}
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    white: pwm_w

output:
  - platform: esp8266_pwm
    pin: GPIO5
    frequency: 1000 Hz
    id: pwm_r

  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 1000 Hz
    id: pwm_g

  - platform: esp8266_pwm
    pin: GPIO13
    frequency: 1000 Hz
    id: pwm_b

  - platform: esp8266_pwm
    pin: GPIO15
    frequency: 1000 Hz
    id: pwm_w
