packages:
  network: !include network.yaml

esphome:
  name: ${name}
  # on_boot:
  #   priority: 200
  #   then:
  #       - wait_until:
  #          condition:
  #             wifi.connected:
  #          timeout: 10s

# Enable logging
logger:

ota:
  - platform: esphome
    password: !secret ota_password

safe_mode:
    reboot_timeout: 3min
    num_attempts: 3


