- platform: places
  name: location_gsm
  devicetracker_id: device_tracker.gsm_mi8
  api_key: tcat.hu@gmail.com
- platform: places
  name: location_gt
  devicetracker_id: device_tracker.gt_xm12
  api_key: gt@kani.hu
