- platform: places
  name: location_gsm
  devicetracker_id: device_tracker.mi_9_lite
  api_key: abcd@kani.hu
- platform: places
  name: location_gt
  devicetracker_id: device_tracker.gt_mi8
  api_key: gt@kani.hu
