packages:
  board: !include _includes/relay_x8.yaml

substitutions:
  name: ac_relay
  hostname: ac-relay
  sw_icon: "mdi:switch"
  sw1_name: bedroom
  sw1_inverted: "yes"
  sw2_name: study
  sw3_name: livingroom
  sw4_name: childb
  sw5_name: childa
  sw6_name: kitchen
  sw7_name: sw7
  sw8_name: ventillation
  sw8_inverted: "yes"
  sw8_restore_mode: RESTORE_DEFAULT_ON
