packages:
  t_tuya: !include _includes/relay_x8.yaml

substitutions:
  name: ac_relay
  sw_icon: "mdi:switch"
  sw1_name: bedroom
  sw1_inverted: "yes"
  sw2_name: study
  sw3_name: livingroom
  sw4_name: childb
  sw5_name: childa
  sw6_name: kitchen
  sw7_name: sw7
  sw8_name: ventillation

dallas:
  - pin: GPIO2
    update_interval: 20s

sensor:
  - platform: dallas
    id: temp1
    name: ac_sensor_temp_ac_outlet
    address: 0x9902099246320028
    filters:
      - offset: 0
  - platform: dallas
    id: temp2
    name: ac_sensor_temp_ac_gas_tube
    address: 0x99020791775C3828
    filters:
      - offset: 0
      
