substitutions:
  name: ac_sensor

packages:
  common: !include _includes/common.yaml
  board: !include _includes/board/esp01.yaml

dallas:
  - pin: GPIO0
    update_interval: 20s

sensor:
  - platform: dallas
    id: temp1
    name: ${name}_temp_ac_outlet
    address: 0x9902099246320028
    filters:
      - offset: 0
  - platform: dallas
    id: temp2
    name: ${name}_temp_ac_gas_tube
    address: 0x99020791775C3828
    filters:
      - offset: 0
