substitutions:
  name: connector
  hostname: connector

packages:
  common: !include _includes/common.yaml
  board: !include _includes/board/esp01.yaml
    
sensor:
  - platform: dht
    model: DHT11
    pin: GPIO0
    update_interval: 15s
    temperature:
      id: temp
      name: ${name}_temp
      filters:
        - offset: 0
        #- exponential_moving_average:
        #    alpha: 0.75
        #    send_every: 4
        #-   sliding_window_moving_average:
        - median:
            window_size: 4 
            send_every: 4 
            send_first_at: 4
    humidity:
      id: humidity
      name: ${name}_humidity
      filters:
        #- exponential_moving_average:
        #    alpha: 0.75
        #    send_every: 4
        #- sliding_window_moving_average:
        - median:
            window_size: 4 
            send_every: 4 
            send_first_at: 4
