substitutions:
  name: energy2
  hostname: energy2

packages:
  common: !include _includes/common.yaml
  board: !include _includes/board/d1_mini.yaml

logger:
  level: INFO

uart:
  - id: ubus1
    rx_pin: D2
    tx_pin: D1
    baud_rate: 9600
    #stop_bits: 2

modbus:
  - id: mbus1
    uart_id: ubus1
    
sensor:
  - platform: pzemac
    modbus_id: mbus1
    address: 1
    current:
      name: ${name}_current
      device_class: current
      state_class: measurement
      icon: mdi:current-ac
    voltage:
      name: ${name}_voltage
      device_class: voltage
      state_class: measurement
      icon: mdi:flash-outline
    energy:
      name: ${name}_energy
      device_class: energy
      unit_of_measurement: Wh
      state_class: total_increasing
      icon: mdi:counter
    power:
      name: ${name}_power
      device_class: power
      unit_of_measurement: W
      state_class: measurement
      icon: mdi:flash
    frequency:
      name: ${name}_freq
      device_class: frequency
      unit_of_measurement: Hz
      state_class: measurement
      icon: mdi:current-ac
    power_factor:
      name: ${name}_pf
      device_class: power_factor
      state_class: measurement
      icon: mdi:percent

    update_interval: 3s
  - platform: dht
    model: DHT11
    pin: D3
    update_interval: 15s
    temperature:
      id: temp
      name: ${name}_temp
      filters:
        - offset: -2
        #- exponential_moving_average:
        #    alpha: 0.75
        #    send_every: 4
        #-   sliding_window_moving_average:
        - median:
            window_size: 4
            send_every: 4
            send_first_at: 4
    humidity:
      id: humidity
      name: ${name}_humidity
      filters:
        #- exponential_moving_average:
        #    alpha: 0.75
        #    send_every: 4
        #- sliding_window_moving_average:
        - median:
            window_size: 4
            send_every: 4
            send_first_at: 4

switch:
  - platform: uart
    uart_id: ubus1
    name: ${name}_reset
    data: [0x01, 0x42, 0x80, 0x11]
