substitutions:
  name: esp32-2432s028

esp32:
  board: esp32dev
  framework:
    type: arduino

packages:
  common: !include _includes/common.yaml
#  fonts: !include _includes/fonts3.yaml
#  color: !include _includes/color.yaml

globals:
  - id: brightness
    type: int
    restore_value: true
    initial_value: '100'

spi:
  - id: lcd_spi
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin: GPIO12
  - id: touch_spi
    clk_pin: GPIO25
    mosi_pin: GPIO32
    miso_pin: GPIO39

i2c:
  sda: GPIO27
  scl: GPIO22
  scan: true
  id: i2c_bus

display:
  - platform: ili9xxx
    model: ILI9341
    id: lcd_display
    spi_id: lcd_spi
    cs_pin: 15
    dc_pin: 2
    auto_clear_enabled: false
    dimensions:
        width: 320
        height: 240

    #rotation: 180
    transform:
        swap_xy: false
        mirror_x: true
        mirror_y: false
#    lambda: |-
#      auto touch = id(touch_screen)->get_touch();
#      if (touch) // or touch.has_value()
#        it.filled_circle(touch.value().x, touch.value().y, 10, RED);

touchscreen:
  platform: xpt2046
  id: touch_screen
  spi_id: touch_spi
  cs_pin: 33
  interrupt_pin: 36
  update_interval: 50ms
  #report_interval: 1s
  threshold: 400
  calibration:
    x_min: 265
    x_max: 3800
    y_min: 280
    y_max: 3620
  transform:
    swap_xy: true
    mirror_x: true
    mirror_y: true
  on_touch:
    then:
      - lvgl.label.update:
          id: text_title
          text:
            format: "x=%d, y=%d\nx_raw=%d, y_raw=%d"
            args: [ touch.x, touch.y, touch.x_raw, touch.y_raw ]
  on_release:
    then:
      - if:
          condition: lvgl.is_paused
          then:
            - light.turn_on: backlight
            - lvgl.resume:
            - lvgl.widget.redraw:

binary_sensor:
  - platform: touchscreen
    name: ${name}_power
    x_min: 30
    x_max: 90
    y_min: 20
    y_max: 80

  - platform: touchscreen
    name: ${name}_music
    x_min: 150
    x_max: 210
    y_min: 20
    y_max: 80

  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    name: ${name}_button0
    id: button0

text_sensor:
  # - platform: template
  #   id: uptime_human
  #   icon: mdi:clock-start
  #   internal: true

  - platform: wifi_info
    ip_address:
      id: ip_address
      internal: true
      on_value:
        - lvgl.label.update:
            id: text_title
            text:
              format: "IP: %s"
              args: [ x.c_str() ]

sensor:
  # - platform: uptime
  #   internal: true
  #   id: uptime_sensor
  #   update_interval: 1s
  #   on_raw_value:
  #     then:
  #       - text_sensor.template.publish:
  #           id: uptime_human
  #           state: !lambda |-
  #             int seconds = round(id(uptime_sensor).raw_state);
  #             int days = seconds / (24 * 3600);
  #             seconds = seconds % (24 * 3600);
  #             int hours = seconds / 3600;
  #             seconds = seconds % 3600;
  #             int minutes = seconds /  60;
  #             seconds = seconds % 60;
  #             return (
  #               ("Uptime ") +
  #               (days ? to_string(days) + "d " : "") +
  #               (hours ? to_string(hours) + "h " : "") +
  #               (minutes ? to_string(minutes) + "m " : "") +
  #               (to_string(seconds) + "s")
  #             ).c_str();

# Define pins for backlight display and back LED1
output:
  - platform: ledc
    pin: GPIO21
    id: output_backlight
  - platform: ledc
    id: output_red
    pin: GPIO4
    inverted: true
  - platform: ledc
    id: output_green
    pin: GPIO16
    inverted: true
  - platform: ledc
    id: output_blue
    pin: GPIO17
    inverted: true

# Define a monochromatic, dimmable light for the backlight
light:
  - platform: monochromatic
    name: ${name}_backlight
    id: backlight
    internal: true
    output: output_backlight
    restore_mode: ALWAYS_ON
  - platform: rgb
    id: led
    internal: true
    red: output_red
    green: output_green
    blue: output_blue
    restore_mode: ALWAYS_OFF
  - platform: lvgl
    id: light_magichome_rgb
    led: led_magichome_rgb
    internal: true

number:
  - platform: lvgl
    widget: slider_brightness
    id: screen_brightness
    internal: true
    on_value:
      - globals.set:
          id: brightness
          value: !lambda return x;
      - light.turn_on:
          id: backlight
          brightness: !lambda |-
            // output value must be in range 0 - 1.0
            // id(backlight).turn_on().set_brightness(x / 100.0).perform()
            return x / 100.0;


# Exposed switches.
switch:
  - platform: homeassistant
    id: l_office_led0
    entity_id: light.l_office_led0
    on_turn_on:
      - lvgl.matrix.button.update:
          id: btn_l_office_led0
          selected: true
    on_turn_off:
      - lvgl.matrix.button.update:
          id: btn_l_office_led0
          selected: false
  - platform: restart
    name: ${name} Restart

# https://fonts.google.com/icons?icon.size=24
font:
  - file: "gfonts://Material+Symbols+Outlined"
    id: icons_24
    size: 24
    glyphs: [
        "\U0000f8b5", # air-conditioner
        "\U0000e0f0", # bulb
        "\U0000e8b8"  # cog
    ]

lvgl:
  displays:
    - lcd_display
  touchscreens:
    - touch_screen
  buffer_size: 20%
  log_level: WARN
  on_idle:
    timeout: 300s
    then:
      - logger.log: "LVGL is idle"
      - lvgl.pause:
      - light.turn_off:
          id: backlight
          transition_length: 5s
  disp_bg_color: 0x000000
  default_font: montserrat_14
  style_definitions:
    - id: black_style
      text_color: 0xFFFFFF
      bg_color: 0x111111
      bg_grad_color: 0xFFFFFF
      border_color: 0x333333
      outline_color: 0xFFFFFF
      shadow_color: 0xFFFFFF
      bg_opa: TRANSP
  styles: black_style
  theme:
    label:
      styles: black_style
    tabview:
      styles: black_style
    button:
      bg_color: 0x333333
      #bg_grad_color: 0x333333
      #bg_grad_dir: VER
      bg_opa: 85%
      border_color: 0x333333
      border_width: 0
      text_color: 0xFFFFFF
      pressed: # set some btn colors to be different in pressed state
        bg_color: 0x111111
        bg_grad_color: 0x111111
      checked: # set some btn colors to be different in checked state
        bg_color: 0x111111
        bg_grad_color: 0x111111
        text_color: 0xf6ff00
    buttonmatrix:
      bg_opa: TRANSP
      border_color: 0x333333
      border_width: 0
      text_color: 0xFFFFFF
      pad_all: 0
      items: # set all your btnmatrix buttons to use your custom defined styles and font
        bg_color: 0x333333
        bg_grad_color: 0x333333
        bg_grad_dir: VER
        bg_opa: COVER
        border_color: 0x333333
        border_width: 1
        text_color: 0xFFFFFF
        pressed:
          bg_color: 0x111111
          bg_grad_color: 0x111111
        checked:
          bg_color: 0x111111
          bg_grad_color: 0x111111
          text_color: 0xEEEEEE
    switch:
      bg_color: 0xC0C0C0
      bg_grad_color: 0xb0b0b0
      bg_grad_dir: VER
      bg_opa: COVER
      checked:
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        bg_grad_dir: VER
        bg_opa: COVER
      knob:
        bg_color: 0xFFFFFF
        bg_grad_color: 0xC0C0C0
        bg_grad_dir: VER
        bg_opa: COVER
    slider:
      border_width: 1
      border_opa: 30%
      bg_color: 0x9c9c9c
      bg_opa: 15%
      indicator:
        bg_color: 0x333333
        bg_grad_color: 0x333333
        bg_opa: COVER
      knob:
        bg_color: 0x444444
        bg_grad_color: 0x444444
        bg_opa: COVER
        border_color: 0x444444
        border_width: 1
        text_color: 0xFFFFFF
  top_layer:
    layout:
      type: flex
      pad_row: 0
      pad_column: 0
      flex_flow: ROW
      flex_align_main: SPACE_BETWEEN # justify-content
      flex_align_cross: CENTER # align-items
      flex_align_track: START # align-content
    widgets:
      - label:
          id: text_title
          text: 'Hello World!'
          width: 70%
          height: 35
      - slider:
          id: slider_brightness
          width: 30%
          pad_top: 10
          min_value: 5
          max_value: 100
          value: !lambda return id(brightness);
      - keyboard:
          id: keyboard
          textarea: textarea_id
          hidden: true
          floating: true
          ignore_layout: true
          on_ready:
            then:
              - lvgl.widget.hide: keyboard
          on_cancel:
            then:
              - lvgl.widget.hide: keyboard
  pages:
    - id: main_page
      pad_top: 38
      widgets:
        - tabview:
            id: tabview_id
            position: top
            size: 15%
            styles: black_style
            text_font: montserrat_14
            tab_style:
              styles: black_style
              text_font: icons_24
              items:
                styles: black_style
                text_font: icons_24
            tabs:
              - name: "\U0000e0f0"
                layout:
                  type: flex
                  pad_row: 4
                  pad_column: 0
                  flex_flow: COLUMN
                  flex_align_main: CENTER # justify-content
                  flex_align_cross: CENTER # align-items
                  flex_align_track: CENTER # align-content
                widgets:
                  - buttonmatrix:
                      height: 60%
                      items:
                        text_font: icons_24
                      rows:
                        - buttons:
                          - id: btn_l_office_led0
                            text: "\U0000e0f0"
                            #selected: !lambda return id(l_office_led0).state
                            control:
                              checkable: true
                              no_repeat: true
                            on_value:
                              then:
                                - logger.log:
                                    format: "Button pressed: %u"
                                    args: [ x ]
                                - if:
                                    condition:
                                      lambda: "return x == true;"
                                    ## todo: create script with x as input
                                    then:
                                      - homeassistant.service:
                                          service: light.turn_on
                                          data:
                                            entity_id: light.l_office_led0
                                    else:
                                      - homeassistant.service:
                                          service: light.turn_off
                                          data:
                                            entity_id: light.l_office_led0
                        # - buttons
                        #   - id: ...
                  - led:
                      id: led_magichome_rgb
                      height: 20%
                      align: CENTER
                      color: 0xFF0000

              - name: "\U0000f8b5"
                layout:
                  type: flex
                  pad_row: 4
                  pad_column: 0
                  flex_flow: COLUMN
                  flex_align_main: CENTER # justify-content
                  flex_align_cross: CENTER # align-items
                  flex_align_track: CENTER # align-content
                widgets:
                  - arc:
                      id: arc_id
                      value: 24
                      min_value: 19
                      max_value: 27
                      adjustable: true

              - name: "\U0000e8b8"
                layout:
                  type: flex
                  pad_row: 4
                  pad_column: 0
                  flex_flow: COLUMN
                  flex_align_main: CENTER # justify-content
                  flex_align_cross: CENTER # align-items
                  flex_align_track: CENTER # align-content
                widgets:
                  - label:
                      text: "Textarea"
                  - textarea:
                      id: textarea_id
                      one_line: true
                      placeholder_text: "Enter text here"
                      on_focus:
                        then:
                          - lvgl.keyboard.update:
                              id: keyboard
                              textarea: textarea_id
                          - lvgl.widget.show: keyboard
                      on_defocus:
                        then:
                          - lvgl.widget.hide: keyboard
                      on_value:
                        then:
                          - logger.log:
                              format: "Textarea changed to: %s"
                              args: [ text.c_str() ]
                      on_ready:
                        then:
                          - logger.log:
                              format: "Textarea ready: %s"
                              args: [ text.c_str() ]
