substitutions:
  name: espcam1

packages:
  common: !include _includes/common.yaml
  board: !include _includes/board/esp32dev.yaml

logger:
  level: DEBUG
  logs:
    sensor: INFO
    esp32_camera: INFO
  baud_rate: 0

esp32_camera:
  name: ${name}
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 800x600
  max_framerate: 5fps

binary_sensor:
  - platform: status
    name: ${name}_status
  - platform: gpio
    pin: GPIO3
    name: ${name}_pir
    device_class: motion

output:
  - platform: gpio
    pin: GPIO4
    id: gpio04
light:
  - platform: binary
    output: gpio04
    name: ${name}
