packages:
  common: !include _includes/minimal.yaml

substitutions:
  name: meeting-info
  hostname: meeting-info

esp8266:
  board: d1_mini
  restore_from_flash: true
  #framework:
  #  version: 3.0.2

#i2c:
#  sda: D2
#  scl: D1

text_sensor:
  - platform: homeassistant
    internal: true
    id: chat_time
    entity_id: sensor.teams_chat
    attribute: time
  - platform: homeassistant
    internal: true
    id: chat_from
    entity_id: sensor.teams_chat
    attribute: from
  - platform: homeassistant
    internal: true
    id: chat_content
    entity_id: sensor.teams_chat
    attribute: content
  - platform: homeassistant
    internal: true
    id: meeting1
    entity_id: binary_sensor.cal1_upcoming
  - platform: homeassistant
    internal: true
    id: meeting1_title
    entity_id: binary_sensor.cal1_upcoming
    attribute: summary
  - platform: homeassistant
    internal: true
    id: meeting1_start
    entity_id: binary_sensor.cal1_upcoming
    attribute: start
  - platform: homeassistant
    internal: true
    id: meeting1_end
    entity_id: binary_sensor.cal1_upcoming
    attribute: end

  - platform: homeassistant
    internal: true
    id: meeting2
    entity_id: binary_sensor.cal2_upcoming
  - platform: homeassistant
    internal: true
    id: meeting2_title
    entity_id: binary_sensor.cal2_upcoming
    attribute: summary
  - platform: homeassistant
    internal: true
    id: meeting2_start
    entity_id: binary_sensor.cal2_upcoming
    attribute: start
  - platform: homeassistant
    internal: true
    id: meeting2_end
    entity_id: binary_sensor.cal2_upcoming
    attribute: end

spi:
  clk_pin: D1
  mosi_pin: D3

font:
  - file: '_fonts/slkscr.ttf'
    id: monobig
    size: 32
  - file: '_fonts/NimbusSans-Narrow.ttf'
    id: narrowsmall
    size: 20
  - file: '_fonts/NotoSans-Regular.ttf'
    id: normallarge
    size: 26

display:
  - platform: waveshare_epaper
    cs_pin: D2
    dc_pin: D4
    busy_pin: D5
    model: 1.54inv2 # 200x200
    rotation: 270
    update_interval: 10s
    full_update_every: 60
    lambda: |-
      if (id(itime).now().is_valid()) {
          it.strftime(it.get_width() / 2, 0, id(monobig), TextAlign::TOP_CENTER, "%d %H:%M", id(itime).now());
          if (id(meeting1_title).has_state()) {
              it.printf(0, 54, id(narrowsmall), TextAlign::BOTTOM_LEFT, "%s", id(meeting1_title).state.c_str());
              it.printf(0, 44, id(normallarge), TextAlign::TOP_LEFT, "%s", id(meeting1_start).state.c_str());
          }
          if (id(meeting2_title).has_state()) {
              it.printf(0, 101, id(narrowsmall), TextAlign::BOTTOM_LEFT, "%s", id(meeting2_title).state.c_str());
              it.printf(0, 91, id(normallarge), TextAlign::TOP_LEFT, "%s", id(meeting2_start).state.c_str());
          }
          if (id(chat_time).has_state()) {
              it.printf(0, 130, id(narrowsmall), TextAlign::TOP_LEFT, "%s", id(chat_from).state.c_str());
              it.printf(0, 153, id(narrowsmall), TextAlign::TOP_LEFT, "%s", id(chat_content).state.c_str());
          }
      } else {
            it.print(it.get_width() / 2, 0, id(normallarge), TextAlign::TOP_CENTER, "Connecting...");
      }
