substitutions:
  name: prolite_led
  hostname: prolite-led

packages:
  common: !include _includes/common.yaml
  board: !include _includes/board/esp01.yaml

external_components:
  - source: github://oxan/esphome-stream-server

uart:
   id: uart_bus
   tx_pin: GPIO01
   #tx_pin: GPIO15
   rx_pin: GPIO03
   #rx_pin: GPIO13
   baud_rate: 9600

stream_server:
   uart_id: uart_bus
   port: 6638
