substitutions:
  name: t_tuya

esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m
  platformio_options:
    board_build.flash_mode: dout
    board_build.ldscript: eagle.flash.1m.ld
    upload_resetmethod: nodemcu

status_led:
  pin:
    number: GPIO2
    inverted: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} fallback hotspot"
    password: !secret ap_password

captive_portal:

# Enable logging
logger:
  level: DEBUG
  logs:
    climate: INFO
  baud_rate: 0
  #hardware_uart: UART1

# Enable Web server
web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

time:
  - platform: homeassistant
    id: hatime

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

tuya:
  #dpID 1:   "Switch (valve)"       Issue and report  Boolean
  #dpID 2:   "Target temperature"   Issue and report  Integer  Values range:0-37, Pitch1, Scale0, Unit:℃
  #dpID 3:   "Current Temperature"  Only report       Integer  Values range:-9-99, Pitch1, Scale0, Unit:℃
  #dpID 4:   "Mode"                 Issue and report  Enum  Enumerated values:m, p (wip)
  #dpID 5:   "Eco mode",            Issue and report, Function type 1 (boolean, Tuyasend1)
  #dpID 6:   "Locked mode",         Issue and report, Function type 1 (boolean, Tuyasend1)
  #dpID 102: "System mode",         Issue and report, Function type 4 (enum?, Tuyasend4), options: 0 cooling, 1 heating, 2 ventilating
  #dpID 103: "Fan speed",           Issue and report, Function type 4 (enum?, Tuyasend4), options: 0 auto, 1 high, 2 medium, 3 low

climate:
  - platform: tuya
    name: ${name}
    switch_datapoint: 1
    target_temperature_datapoint: 2
    current_temperature_datapoint: 3
    temperature_multiplier: 0.5

switch:
  - platform: tuya
    name: ${name}_eco_mode
    switch_datapoint: 5
  - platform: tuya
    name: ${name}_locked_mode
    switch_datapoint: 6

sensor:
  - platform: tuya
    name: ${name}_mode
    sensor_datapoint: 4
  - platform: tuya
    name: ${name}_system_mode
    sensor_datapoint: 102

fan:
  - platform: tuya
    name: ${name}
    switch_datapoint: 1
    speed_datapoint: 103
